### ISSUE TITLE
BAYC (Mobile)

### ISSUE THREAD

**Issue by FanFanDAO** [popcorndao/bayc-onboarding#3]
### We building the mobile experience of the airdrop partnership programs. For this project, it will be for BAYC.
The desktop and mobile versions will be repurposed for other partnerships in the future.

## Source File
- https://www.figma.com/file/AEfyqvQLZ5XxlWfi1mehzT/%5BPopcorn%5D-Website?node-id=2571%3A24726

## Key Development Requirements
- Clean, lean, and organized code practices
- The top header SVG art should switch to this new one shown in the images below for mobiles. (The bored ape is combined with the header SVG)
- Animation from the desktop view should ideally be translated into mobile (Please inform if there is a technical blocker)
- The module height should be fixed for both mobile and desktop
- Spacings, colors, effects, and fonts should be the same as the design.
- This page and the entire UX flow should be adaptive with fluid transition across all mobile browser sizes.
- This page and the entire UX flow that follows should display and work normally across all versions of commonly used browsers (e.g., Chrome, Firefox, Safari, Internet Explorer, Opera; etc.).

## Vibe
Our customer success depends on this touchpoint experience you are making. So you are the hero, don't forget! Love love. :)

## Image Reference
![Landing Page.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f6adc8b8-7b7e-4fe9-95db-aaf5e84ba9c1)
![Landing Page-2.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/0c62e4a2-cfd3-4828-b108-7bb6f6beb633)
![Landing Page-3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/47a17536-0dc7-4699-b3d1-1626056d90df)
![2021.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/55ca1c1e-4266-4135-b066-762c0f855a0d)
![Landing Page-1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/a28f1e8e-8d45-44df-9ce7-47566861ea1a)

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/bayc-onboarding/pull/6
Preview: https://deploy-preview-6--bayc-onboarding.netlify.app/
